const router = require("express").Router();
const categoryRouter = require("../routes/category.routes");
const regionRouter = require("../routes/region.routes");
const districtRouter = require("../routes/district.routes");
const commissionRouter = require("../routes/commission.routes");
const statusRouter = require("../routes/status.routes");
const imageRouter = require("../routes/image.routes");
const usersRouter = require("../routes/users.routes");
const useraddressRouter = require("../routes/user_address.routes");
const machineRouter = require("../routes/machine.routes");
const reviewRouter = require("../routes/review.routes");
const roleRouter = require("../routes/role.routes");
const userRoleRouter = require("./user_role.routes");
const authRouter = require("./auth.routes");
const contractRouter = require("./contract.routes");
const paymentRouter = require("./payment.routes");

router.use("/category", categoryRouter);
router.use("/region", regionRouter);
router.use("/district", districtRouter);
router.use("/commission", commissionRouter);
router.use("/status", statusRouter);
router.use("/image", imageRouter);
router.use("/users", usersRouter);
router.use("/useraddress", useraddressRouter);
router.use("/machine", machineRouter);
router.use("/review", reviewRouter);
router.use("/role", roleRouter);
router.use("/user-role", userRoleRouter);
router.use("/auth", authRouter);
router.use("/contract", contractRouter);
router.use("/payment", paymentRouter);

module.exports = router;
